const ACTION_ADD = 'ADD';
const ACTION_MINUS = 'MINUS';
const ASYNC_ACTION_ADD = 'ASYNC_ADD';
const ASYNC_ACTION_MINUS = 'ASYNC_MINUS';
const CANCEL_ADD = 'CANCEL_ADD';

export {
  ACTION_ADD,
  ACTION_MINUS,
  ASYNC_ACTION_ADD,
  ASYNC_ACTION_MINUS,
  CANCEL_ADD,
};
