const webpack = require('webpack');
const config = require('../webpack.config');

const complier = webpack(config);

debugger;
complier.run((err, stats) => {
  const res = stats.toJson({
    files: true,
    assets: true,
    chunks: true,
    module: true,
    entries: true,
  });
  console.log(JSON.stringify(res, null, 2));
});

const res = {
  hash: '7a02dade9f9d7ce3d36d',
  version: '5.40.0',
  time: 116,
  builtAt: 1624519029575,
  publicPath: 'auto',
  outputPath: '/workspace/bfe-go/micro/webpack-flow/dist',
  assetsByChunkName: {
    main: ['main.js'],
  },
  assets: [
    {
      type: 'asset',
      name: 'main.js',
      size: 1254,
      emitted: false,
      comparedForEmit: true,
      cached: false,
      info: {
        javascriptModule: false,
        size: 1254,
      },
      chunkNames: ['main'],
      chunkIdHints: [],
      auxiliaryChunkNames: [],
      auxiliaryChunkIdHints: [],
      related: {},
      chunks: ['main'],
      auxiliaryChunks: [],
      isOverSizeLimit: false,
    },
    {
      type: 'asset',
      name: 'index.html',
      size: 231,
      emitted: false,
      comparedForEmit: true,
      cached: false,
      info: {
        size: 231,
      },
      chunkNames: [],
      chunkIdHints: [],
      auxiliaryChunkNames: [],
      auxiliaryChunkIdHints: [],
      related: {},
      chunks: [],
      auxiliaryChunks: [],
      isOverSizeLimit: false,
    },
  ],
  chunks: [
    {
      rendered: true,
      initial: true,
      entry: true,
      recorded: false,
      size: 41,
      sizes: {
        javascript: 41,
      },
      names: ['main'],
      idHints: [],
      runtime: ['main'],
      files: ['main.js'],
      auxiliaryFiles: [],
      hash: 'd3308e29b05d2122c875',
      childrenByOrder: {},
      id: 'main',
      siblings: [],
      parents: [],
      children: [],
      modules: [
        {
          type: 'module',
          moduleType: 'javascript/auto',
          layer: null,
          size: 41,
          sizes: {
            javascript: 41,
          },
          built: true,
          codeGenerated: true,
          buildTimeExecuted: false,
          cached: false,
          identifier: '/workspace/bfe-go/micro/webpack-flow/src/index.js',
          name: './src/index.js',
          nameForCondition: '/workspace/bfe-go/micro/webpack-flow/src/index.js',
          index: 0,
          preOrderIndex: 0,
          index2: 0,
          postOrderIndex: 0,
          cacheable: true,
          optional: false,
          orphan: false,
          dependent: false,
          issuer: null,
          issuerName: null,
          issuerPath: null,
          failed: false,
          errors: 0,
          warnings: 0,
          id: './src/index.js',
          issuerId: null,
          chunks: ['main'],
          assets: [],
          reasons: [
            {
              moduleIdentifier: null,
              module: null,
              moduleName: null,
              resolvedModuleIdentifier: null,
              resolvedModule: null,
              type: 'entry',
              active: true,
              explanation: '',
              userRequest: './src/index.js',
              loc: 'main',
              moduleId: null,
              resolvedModuleId: null,
            },
          ],
          usedExports: null,
          providedExports: null,
          optimizationBailout: [],
          depth: 0,
        },
      ],
      origins: [
        {
          module: '',
          moduleIdentifier: '',
          moduleName: '',
          loc: 'main',
          request: './src/index.js',
        },
      ],
    },
  ],
  modules: [
    {
      type: 'module',
      moduleType: 'javascript/auto',
      layer: null,
      size: 41,
      sizes: {
        javascript: 41,
      },
      built: true,
      codeGenerated: true,
      buildTimeExecuted: false,
      cached: false,
      identifier: '/workspace/bfe-go/micro/webpack-flow/src/index.js',
      name: './src/index.js',
      nameForCondition: '/workspace/bfe-go/micro/webpack-flow/src/index.js',
      index: 0,
      preOrderIndex: 0,
      index2: 0,
      postOrderIndex: 0,
      cacheable: true,
      optional: false,
      orphan: false,
      issuer: null,
      issuerName: null,
      issuerPath: null,
      failed: false,
      errors: 0,
      warnings: 0,
      id: './src/index.js',
      issuerId: null,
      chunks: ['main'],
      assets: [],
      reasons: [
        {
          moduleIdentifier: null,
          module: null,
          moduleName: null,
          resolvedModuleIdentifier: null,
          resolvedModule: null,
          type: 'entry',
          active: true,
          explanation: '',
          userRequest: './src/index.js',
          loc: 'main',
          moduleId: null,
          resolvedModuleId: null,
        },
      ],
      usedExports: null,
      providedExports: null,
      optimizationBailout: [],
      depth: 0,
    },
  ],
  entrypoints: {
    main: {
      name: 'main',
      chunks: ['main'],
      assets: [
        {
          name: 'main.js',
          size: 1254,
        },
      ],
      filteredAssets: 0,
      assetsSize: 1254,
      auxiliaryAssets: [],
      filteredAuxiliaryAssets: 0,
      auxiliaryAssetsSize: 0,
      children: {},
      childAssets: {},
      isOverSizeLimit: false,
    },
  },
  namedChunkGroups: {
    main: {
      name: 'main',
      chunks: ['main'],
      assets: [
        {
          name: 'main.js',
          size: 1254,
        },
      ],
      filteredAssets: 0,
      assetsSize: 1254,
      auxiliaryAssets: [],
      filteredAuxiliaryAssets: 0,
      auxiliaryAssetsSize: 0,
      children: {},
      childAssets: {},
      isOverSizeLimit: false,
    },
  },
  errors: [],
  errorsCount: 0,
  warnings: [],
  warningsCount: 0,
  children: [
    {
      name: 'HtmlWebpackCompiler',
      hash: 'afe2e30c34d6b7ffb75f',
      version: '5.40.0',
      time: 87,
      builtAt: 1624519029565,
      publicPath: '',
      outputPath: '/workspace/bfe-go/micro/webpack-flow/dist',
      assetsByChunkName: {},
      assets: [],
      chunks: [
        {
          rendered: true,
          initial: true,
          entry: true,
          recorded: false,
          size: 1248,
          sizes: {
            javascript: 514,
            runtime: 734,
          },
          names: ['HtmlWebpackPlugin_0-0'],
          idHints: [],
          runtime: ['HtmlWebpackPlugin_0-0'],
          files: [],
          auxiliaryFiles: [],
          hash: 'e5d3550f589f5e2d54cd',
          childrenByOrder: {},
          id: 'HtmlWebpackPlugin_0-0',
          siblings: [],
          parents: [],
          children: [],
          modules: [
            {
              type: 'module',
              moduleType: 'javascript/auto',
              layer: null,
              size: 437,
              sizes: {
                javascript: 437,
              },
              built: true,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier:
                '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/lib/loader.js!/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
              name:
                './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
              nameForCondition:
                '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
              index: 1,
              preOrderIndex: 1,
              index2: 1,
              postOrderIndex: 1,
              cacheable: true,
              optional: false,
              orphan: false,
              dependent: false,
              issuer: null,
              issuerName: null,
              issuerPath: null,
              failed: false,
              errors: 0,
              warnings: 0,
              id:
                './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
              issuerId: null,
              chunks: ['HtmlWebpackPlugin_0-0'],
              assets: [],
              reasons: [
                {
                  moduleIdentifier:
                    '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/lib/loader.js!/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
                  module:
                    './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
                  moduleName:
                    './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
                  resolvedModuleIdentifier:
                    '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/lib/loader.js!/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
                  resolvedModule:
                    './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
                  type: 'cjs self exports reference',
                  active: true,
                  explanation: '',
                  userRequest: null,
                  loc: '1:102-116',
                  moduleId:
                    './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
                  resolvedModuleId:
                    './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
                },
                {
                  moduleIdentifier: null,
                  module: null,
                  moduleName: null,
                  resolvedModuleIdentifier: null,
                  resolvedModule: null,
                  type: 'entry',
                  active: true,
                  explanation: '',
                  userRequest:
                    '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/lib/loader.js!/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
                  loc: 'HtmlWebpackPlugin_0-0',
                  moduleId: null,
                  resolvedModuleId: null,
                },
                {
                  moduleIdentifier: null,
                  module: null,
                  moduleName: null,
                  resolvedModuleIdentifier: null,
                  resolvedModule: null,
                  type: null,
                  active: true,
                  explanation: 'used as library export',
                  userRequest: null,
                  moduleId: null,
                  resolvedModuleId: null,
                },
              ],
              usedExports: null,
              providedExports: null,
              optimizationBailout: [
                'CommonJS bailout: module.exports is used directly at 1:102-116',
              ],
              depth: 0,
            },
            {
              type: 'module',
              moduleType: 'javascript/esm',
              layer: null,
              size: 77,
              sizes: {
                javascript: 77,
              },
              built: true,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier:
                'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
              name:
                'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
              nameForCondition:
                'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
              index: 0,
              preOrderIndex: 0,
              index2: 0,
              postOrderIndex: 0,
              cacheable: true,
              optional: false,
              orphan: false,
              dependent: false,
              issuer: null,
              issuerName: null,
              issuerPath: null,
              failed: false,
              errors: 0,
              warnings: 0,
              id:
                'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
              issuerId: null,
              chunks: ['HtmlWebpackPlugin_0-0'],
              assets: [],
              reasons: [
                {
                  moduleIdentifier: null,
                  module: null,
                  moduleName: null,
                  resolvedModuleIdentifier: null,
                  resolvedModule: null,
                  type: 'entry',
                  active: true,
                  explanation: '',
                  userRequest:
                    'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
                  loc: 'HtmlWebpackPlugin_0-0',
                  moduleId: null,
                  resolvedModuleId: null,
                },
              ],
              usedExports: null,
              providedExports: [],
              optimizationBailout: [],
              depth: 0,
            },
            {
              type: 'module',
              moduleType: 'runtime',
              layer: null,
              size: 88,
              sizes: {
                runtime: 88,
              },
              built: false,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier: 'webpack/runtime/hasOwnProperty shorthand',
              name: 'webpack/runtime/hasOwnProperty shorthand',
              nameForCondition: null,
              index: null,
              preOrderIndex: null,
              index2: null,
              postOrderIndex: null,
              optional: false,
              orphan: false,
              dependent: false,
              failed: false,
              errors: 0,
              warnings: 0,
              id: '',
              chunks: ['HtmlWebpackPlugin_0-0'],
              assets: [],
              reasons: [],
              usedExports: null,
              providedExports: [],
              optimizationBailout: [],
              depth: null,
            },
            {
              type: 'module',
              moduleType: 'runtime',
              layer: null,
              size: 274,
              sizes: {
                runtime: 274,
              },
              built: false,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier: 'webpack/runtime/make namespace object',
              name: 'webpack/runtime/make namespace object',
              nameForCondition: null,
              index: null,
              preOrderIndex: null,
              index2: null,
              postOrderIndex: null,
              optional: false,
              orphan: false,
              dependent: false,
              failed: false,
              errors: 0,
              warnings: 0,
              id: '',
              chunks: ['HtmlWebpackPlugin_0-0'],
              assets: [],
              reasons: [],
              usedExports: null,
              providedExports: [],
              optimizationBailout: [],
              depth: null,
            },
            {
              type: 'module',
              moduleType: 'runtime',
              layer: null,
              size: 27,
              sizes: {
                runtime: 27,
              },
              built: false,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier: 'webpack/runtime/publicPath',
              name: 'webpack/runtime/publicPath',
              nameForCondition: null,
              index: null,
              preOrderIndex: null,
              index2: null,
              postOrderIndex: null,
              optional: false,
              orphan: false,
              dependent: false,
              failed: false,
              errors: 0,
              warnings: 0,
              id: '',
              chunks: ['HtmlWebpackPlugin_0-0'],
              assets: [],
              reasons: [],
              usedExports: null,
              providedExports: [],
              optimizationBailout: [],
              depth: null,
            },
            {
              type: 'module',
              moduleType: 'runtime',
              layer: null,
              size: 345,
              sizes: {
                runtime: 345,
              },
              built: false,
              codeGenerated: true,
              buildTimeExecuted: false,
              cached: false,
              identifier: 'webpack/runtime/require chunk loading',
              name: 'webpack/runtime/require chunk loading',
              nameForCondition: null,
              index: null,
              preOrderIndex: null,
              index2: null,
              postOrderIndex: null,
              optional: false,
              orphan: false,
              dependent: false,
              failed: false,
              errors: 0,
              warnings: 0,
              id: '',
              chunks: ['HtmlWebpackPlugin_0-0'],
              assets: [],
              reasons: [],
              usedExports: null,
              providedExports: [],
              optimizationBailout: [],
              depth: null,
            },
          ],
          origins: [
            {
              module: '',
              moduleIdentifier: '',
              moduleName: '',
              loc: 'HtmlWebpackPlugin_0-0',
              request:
                '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/lib/loader.js!/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
            },
            {
              module: '',
              moduleIdentifier: '',
              moduleName: '',
              loc: 'HtmlWebpackPlugin_0-0',
              request:
                'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
            },
          ],
        },
      ],
      modules: [
        {
          type: 'module',
          moduleType: 'javascript/esm',
          layer: null,
          size: 77,
          sizes: {
            javascript: 77,
          },
          built: true,
          codeGenerated: true,
          buildTimeExecuted: false,
          cached: false,
          identifier:
            'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
          name:
            'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
          nameForCondition:
            'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
          index: 0,
          preOrderIndex: 0,
          index2: 0,
          postOrderIndex: 0,
          cacheable: true,
          optional: false,
          orphan: false,
          issuer: null,
          issuerName: null,
          issuerPath: null,
          failed: false,
          errors: 0,
          warnings: 0,
          id:
            'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
          issuerId: null,
          chunks: ['HtmlWebpackPlugin_0-0'],
          assets: [],
          reasons: [
            {
              moduleIdentifier: null,
              module: null,
              moduleName: null,
              resolvedModuleIdentifier: null,
              resolvedModule: null,
              type: 'entry',
              active: true,
              explanation: '',
              userRequest:
                'data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;',
              loc: 'HtmlWebpackPlugin_0-0',
              moduleId: null,
              resolvedModuleId: null,
            },
          ],
          usedExports: null,
          providedExports: [],
          optimizationBailout: [],
          depth: 0,
        },
        {
          type: 'module',
          moduleType: 'javascript/auto',
          layer: null,
          size: 437,
          sizes: {
            javascript: 437,
          },
          built: true,
          codeGenerated: true,
          buildTimeExecuted: false,
          cached: false,
          identifier:
            '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/lib/loader.js!/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
          name:
            './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
          nameForCondition:
            '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
          index: 1,
          preOrderIndex: 1,
          index2: 1,
          postOrderIndex: 1,
          cacheable: true,
          optional: false,
          orphan: false,
          issuer: null,
          issuerName: null,
          issuerPath: null,
          failed: false,
          errors: 0,
          warnings: 0,
          id:
            './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
          issuerId: null,
          chunks: ['HtmlWebpackPlugin_0-0'],
          assets: [],
          reasons: [
            {
              moduleIdentifier:
                '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/lib/loader.js!/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
              module:
                './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
              moduleName:
                './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
              resolvedModuleIdentifier:
                '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/lib/loader.js!/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
              resolvedModule:
                './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
              type: 'cjs self exports reference',
              active: true,
              explanation: '',
              userRequest: null,
              loc: '1:102-116',
              moduleId:
                './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
              resolvedModuleId:
                './node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs',
            },
            {
              moduleIdentifier: null,
              module: null,
              moduleName: null,
              resolvedModuleIdentifier: null,
              resolvedModule: null,
              type: 'entry',
              active: true,
              explanation: '',
              userRequest:
                '/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/lib/loader.js!/workspace/bfe-go/micro/webpack-flow/node_modules/html-webpack-plugin/default_index.ejs',
              loc: 'HtmlWebpackPlugin_0-0',
              moduleId: null,
              resolvedModuleId: null,
            },
            {
              moduleIdentifier: null,
              module: null,
              moduleName: null,
              resolvedModuleIdentifier: null,
              resolvedModule: null,
              type: null,
              active: true,
              explanation: 'used as library export',
              userRequest: null,
              moduleId: null,
              resolvedModuleId: null,
            },
          ],
          usedExports: null,
          providedExports: null,
          optimizationBailout: [
            'CommonJS bailout: module.exports is used directly at 1:102-116',
          ],
          depth: 0,
        },
        {
          type: 'module',
          moduleType: 'runtime',
          layer: null,
          size: 88,
          sizes: {
            runtime: 88,
          },
          built: false,
          codeGenerated: true,
          buildTimeExecuted: false,
          cached: false,
          identifier: 'webpack/runtime/hasOwnProperty shorthand',
          name: 'webpack/runtime/hasOwnProperty shorthand',
          nameForCondition: null,
          index: null,
          preOrderIndex: null,
          index2: null,
          postOrderIndex: null,
          optional: false,
          orphan: false,
          failed: false,
          errors: 0,
          warnings: 0,
          id: '',
          chunks: ['HtmlWebpackPlugin_0-0'],
          assets: [],
          reasons: [],
          usedExports: null,
          providedExports: [],
          optimizationBailout: [],
          depth: null,
        },
        {
          type: 'module',
          moduleType: 'runtime',
          layer: null,
          size: 274,
          sizes: {
            runtime: 274,
          },
          built: false,
          codeGenerated: true,
          buildTimeExecuted: false,
          cached: false,
          identifier: 'webpack/runtime/make namespace object',
          name: 'webpack/runtime/make namespace object',
          nameForCondition: null,
          index: null,
          preOrderIndex: null,
          index2: null,
          postOrderIndex: null,
          optional: false,
          orphan: false,
          failed: false,
          errors: 0,
          warnings: 0,
          id: '',
          chunks: ['HtmlWebpackPlugin_0-0'],
          assets: [],
          reasons: [],
          usedExports: null,
          providedExports: [],
          optimizationBailout: [],
          depth: null,
        },
        {
          type: 'module',
          moduleType: 'runtime',
          layer: null,
          size: 27,
          sizes: {
            runtime: 27,
          },
          built: false,
          codeGenerated: true,
          buildTimeExecuted: false,
          cached: false,
          identifier: 'webpack/runtime/publicPath',
          name: 'webpack/runtime/publicPath',
          nameForCondition: null,
          index: null,
          preOrderIndex: null,
          index2: null,
          postOrderIndex: null,
          optional: false,
          orphan: false,
          failed: false,
          errors: 0,
          warnings: 0,
          id: '',
          chunks: ['HtmlWebpackPlugin_0-0'],
          assets: [],
          reasons: [],
          usedExports: null,
          providedExports: [],
          optimizationBailout: [],
          depth: null,
        },
        {
          type: 'module',
          moduleType: 'runtime',
          layer: null,
          size: 345,
          sizes: {
            runtime: 345,
          },
          built: false,
          codeGenerated: true,
          buildTimeExecuted: false,
          cached: false,
          identifier: 'webpack/runtime/require chunk loading',
          name: 'webpack/runtime/require chunk loading',
          nameForCondition: null,
          index: null,
          preOrderIndex: null,
          index2: null,
          postOrderIndex: null,
          optional: false,
          orphan: false,
          failed: false,
          errors: 0,
          warnings: 0,
          id: '',
          chunks: ['HtmlWebpackPlugin_0-0'],
          assets: [],
          reasons: [],
          usedExports: null,
          providedExports: [],
          optimizationBailout: [],
          depth: null,
        },
      ],
      entrypoints: {
        'HtmlWebpackPlugin_0-0': {
          name: 'HtmlWebpackPlugin_0-0',
          chunks: ['HtmlWebpackPlugin_0-0'],
          assets: [],
          filteredAssets: 0,
          assetsSize: 0,
          auxiliaryAssets: [],
          filteredAuxiliaryAssets: 0,
          auxiliaryAssetsSize: 0,
          children: {},
          childAssets: {},
          isOverSizeLimit: false,
        },
      },
      namedChunkGroups: {
        'HtmlWebpackPlugin_0-0': {
          name: 'HtmlWebpackPlugin_0-0',
          chunks: ['HtmlWebpackPlugin_0-0'],
          assets: [],
          filteredAssets: 0,
          assetsSize: 0,
          auxiliaryAssets: [],
          filteredAuxiliaryAssets: 0,
          auxiliaryAssetsSize: 0,
          children: {},
          childAssets: {},
          isOverSizeLimit: false,
        },
      },
      errors: [],
      errorsCount: 0,
      warnings: [],
      warningsCount: 0,
      children: [],
    },
  ],
};
